
applicationName: customers
port: 8080
targetPort: 8080
deploymentStrategy:
  type: RollingUpdate
  rollingMaxSurge: 25%
  rollingMaxUnavailable: 20%
replicaCount: 1
health:
  livenessEndpoint: /health/live
  readinessEndpoint: /health/ready
  probeDelay: 5
  probePeriod: 10
  probeTimeout: 2
imageURL: "quay.io/rromanni/customers:fe-0.2"
env: []
