apiVersion: v2
publisher: GabrielBB
name: vscode-lombok
version: 1.0.1
type: VS Code extension
displayName: Lombok Annotations Support for VS Code
title: Lombok Annotations Support for VS Code
description: A lightweight extension to support Lombok annotations processing in Visual Studio Code
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-plugin-registry/resources/images/default.svg?sanitize=true
repository: https://github.com/GabrielBB/vscode-lombok.git
category: Other
firstPublicationDate: '2018-11-03'
spec:                                                             
  extensions:
  - "https://raw.githubusercontent.com/rromannissen/rhoar-microservices-demo/crw/vscode-lombok-1.0.1.vsix" 
latestUpdateDate: "2020-02-18"
