spring:
  datasource:
    url: jdbc:h2:mem:orders;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        lob:
          non_contextual_creation: true

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-all-in-one-inmemory-collector:14268/api/traces
