
applicationName: inventory
port: 8080
targetPort: 8080
deploymentStrategy:
  type: RollingUpdate
  rollingMaxSurge: 25%
  rollingMaxUnavailable: 20%
replicaCount: 1
health:
  livenessEndpoint: /health/live
  readinessEndpoint: /health/ready
  probeDelay: 5
  probePeriod: 10
  probeTimeout: 2
# imageURL: "quay.io/rromanni/inventory:fe-0.1"
imageURL: "quay.io/rofrano/inventory:0.1"
env: []

# Database variables for bitnami PostgreSQL
postgresql:
  postgresqlDatabase: "inventory"
  postgresqlUsername: "inventory"
  postgresqlPassword: "inventory"
  servicePort: "5432"

# Generate an Ingress
ingress:
  enabled: true
  tls: false
  hostname: inventory.inventory.10.19.2.21.nip.io
  annotations:
    kubernetes.io/ingress.class: haproxy
    # kubernetes.io/ingress.class: "nginx"
    # secretName: my-tls-cert
    # kubernetes.io/tls-acme: "true"